### PR TITLE
refactor makefile: var to inject adoc options; change to build dir instead of outfiles

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rpsene** [comment]
@wmat we will need to revert it. This broke the PDF generation process.

**Comment by wmat** [comment]
Ok go ahead. I can look at it tomorrow.

Bill Traynor
Documentation Build and Release Engineer
RISC-V International

**Comment by rpsene** [comment]
@wmat in fact, we need to review all the commits from the last week. There was a lot of changes and I'm not sure which broke the process.

**Comment by ghost** [comment]
> @wmat we will need to revert it. This broke the PDF generation process.

I think the only problem might be that I didn't tell the action the new location of the pdf.
(Although it would probably be good for the action to fail if it doesn't find a pdf)

I corrected this with  PR #31

I didn't change the action to fail if it doesn't find a pdf.

**Comment by rpsene** [comment]
@kbroch-rivosinc I had to force and push the fix given the necessity to use the template for a new spec. Thanks for the PR :)

**Pull request merged**
